# Generated by Django 5.1.2 on 2025-03-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price_of_time_addition',
            new_name='price_at_time_of_addition',
        ),
    ]
